# Generated by Django 5.1.4 on 2024-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('main_image_url', models.URLField(verbose_name='Ссылка на главную картинку')),
                ('footage_images', models.JSONField(verbose_name='Ссылки на картинки игры')),
                ('genres', models.JSONField(help_text='Список жанров игры', verbose_name='Жанры')),
                ('os', models.CharField(help_text='Например: Windows, macOS, Linux', max_length=100, verbose_name='Операционная система')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издатель')),
                ('developer', models.CharField(max_length=100, verbose_name='Разработчик')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['title'],
            },
        ),
    ]
